basePath: /api/v1
definitions:
  main.Activity:
    properties:
      activity_id:
        type: string
      categorization_distance:
        type: number
      categorization_grade:
        type: string
      categorized:
        type: boolean
      created_at:
        type: string
      duration:
        type: string
      input_description:
        type: string
      jira:
        type: string
      posted_to_jira_tempo:
        type: boolean
      project:
        type: string
      rule_description:
        type: string
      task:
        type: string
      weaviate_id:
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: API for tracking and managing activities
  title: AIdea Activity Tracker API
  version: "1.0"
paths:
  /activity:
    post:
      consumes:
      - application/json
      description: Create a new activity with the provided details
      parameters:
      - description: Activity object to be created
        in: body
        name: activity
        required: true
        schema:
          $ref: '#/definitions/main.Activity'
      produces:
      - application/json
      responses:
        "201":
          description: Successfully created activity
          schema:
            $ref: '#/definitions/main.Activity'
        "400":
          description: Bad request
          schema:
            type: string
        "415":
          description: Unsupported media type
          schema:
            type: string
      summary: Create a new activity
      tags:
      - activity
  /activity/{date}/{id}:
    get:
      description: Get a specific activity by its date and ID
      parameters:
      - description: Date in YYYYMMDD format
        in: path
        name: date
        required: true
        type: string
      - description: Activity ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Activity details
          schema:
            $ref: '#/definitions/main.Activity'
        "400":
          description: Bad request
          schema:
            type: string
        "404":
          description: Activity not found
          schema:
            type: string
      summary: Get activity by date and ID
      tags:
      - activity
  /activity/{id}:
    get:
      description: Get a specific activity by its ID (from today's activities)
      parameters:
      - description: Activity ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Activity details
          schema:
            $ref: '#/definitions/main.Activity'
        "400":
          description: Bad request
          schema:
            type: string
        "404":
          description: Activity not found
          schema:
            type: string
      summary: Get activity by ID
      tags:
      - activity
  /activity/csv/{date}:
    get:
      description: Get all activities recorded on a specific date in CSV format
      parameters:
      - description: Date in YYYYMMDD format
        in: path
        name: date
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: List of activities for the specified date
          schema:
            items:
              $ref: '#/definitions/main.Activity'
            type: array
        "400":
          description: Bad request
          schema:
            type: string
        "404":
          description: No activities found for the specified date
          schema:
            type: string
      summary: Get activities by date
      tags:
      - activity
  /activity/csv/today:
    get:
      description: Get all activities recorded today in CSV format
      produces:
      - application/json
      responses:
        "200":
          description: List of today's activities
          schema:
            items:
              $ref: '#/definitions/main.Activity'
            type: array
        "400":
          description: Bad request
          schema:
            type: string
        "404":
          description: No activities found for today
          schema:
            type: string
      summary: Get today's activities
      tags:
      - activity
  /activity/recategorize/{id}:
    patch:
      consumes:
      - application/json
      description: Recategorize an existing activity by its ID
      parameters:
      - description: Activity ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Successfully recategorized activity
          schema:
            $ref: '#/definitions/main.Activity'
        "400":
          description: Bad request
          schema:
            type: string
        "404":
          description: Activity not found
          schema:
            type: string
      summary: Recategorize an activity
      tags:
      - activity
  /activity/tempo/{date}/{id}:
    post:
      description: Post an activity to Jira/Tempo by its date and ID
      parameters:
      - description: Date in YYYYMMDD format
        in: path
        name: date
        required: true
        type: string
      - description: Activity ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Successfully posted to Jira/Tempo
          schema:
            type: string
        "400":
          description: Bad request
          schema:
            type: string
        "404":
          description: Activity not found
          schema:
            type: string
      summary: Post activity to Jira/Tempo
      tags:
      - activity
swagger: "2.0"
